// Regenerates src/lib/abi.ts from the Foundry build output. Run `npm run abi` after contract changes.
const fs = require("fs");
const path = require("path");
const out = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, `../../contracts/out/${name}.sol/${name}.json`), "utf8")).abi;
const header = "// Generated by scripts/abi-to-ts.js from contracts/out. Do not edit by hand.\n";
const body =
  `export const smartMoneyAbi = ${JSON.stringify(out("SmartMoneyRounds"), null, 2)} as const;\n\n` +
  `export const oracleAbi = ${JSON.stringify(out("PerplOracleAdapter"), null, 2)} as const;\n`;
fs.writeFileSync(path.join(__dirname, "../src/lib/abi.ts"), header + body);
console.log("wrote src/lib/abi.ts");
